name: rdm_example
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - anyio=4.8.0=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py310ha8f682b_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.4=pyhd8ed1ab_1
  - attrs=24.3.0=pyh71513ae_0
  - babel=2.16.0=pyhd8ed1ab_1
  - beautifulsoup4=4.12.3=pyha770c72_1
  - bleach=6.2.0=pyhd8ed1ab_3
  - bleach-with-css=6.2.0=hd8ed1ab_3
  - brotli-python=1.1.0=py310h9e98ed7_2
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2024.12.14=h56e8100_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cadet=5.0.3=h6c8fd53_0
  - certifi=2024.12.14=pyhd8ed1ab_0
  - cffi=1.17.1=py310ha8f682b_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - cpython=3.10.16=py310hd8ed1ab_1
  - debugpy=1.8.11=py310h9e98ed7_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - fqdn=1.5.1=pyhd8ed1ab_1
  - gmp=6.3.0=hfeafd45_2
  - h11=0.14.0=pyhd8ed1ab_1
  - h2=4.1.0=pyhd8ed1ab_1
  - hdf5=1.14.4=nompi_hd5d9e70_105
  - hpack=4.0.0=pyhd8ed1ab_1
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_1
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.5.0=pyha770c72_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2024.2.1=h57928b3_1083
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.31.0=pyh7428d3b_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.5=pyhd8ed1ab_0
  - json5=0.10.0=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py310h5588dad_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh5737063_1
  - jupyter_events=0.11.0=pyhd8ed1ab_0
  - jupyter_server=2.15.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.3.4=pyhd8ed1ab_0
  - jupyterlab-myst=2.4.2=pyhd8ed1ab_1
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - krb5=1.21.3=hdf4eb48_0
  - libaec=1.1.3=h63175ca_0
  - libamd=3.3.3=ss783_h38ac50e
  - libblas=3.9.0=26_win64_mkl
  - libbtf=2.3.2=ss783_hde22806
  - libcamd=3.3.3=ss783_hde22806
  - libcblas=3.9.0=26_win64_mkl
  - libccolamd=3.3.4=ss783_hde22806
  - libcholmod=5.3.0=ss783_h9a56889
  - libcolamd=3.3.4=ss783_hde22806
  - libcurl=8.11.1=h88aaa65_0
  - libcxsparse=4.4.1=ss783_hde22806
  - libffi=3.4.2=h8ffe710_5
  - libgcc=14.2.0=h1383e82_1
  - libgomp=14.2.0=h1383e82_1
  - libhwloc=2.11.2=default_ha69328c_1001
  - libiconv=1.17=hcfcfb64_2
  - libklu=2.3.5=ss783_h77d05f4
  - liblapack=3.9.0=26_win64_mkl
  - libldl=3.3.2=ss783_hde22806
  - liblzma=5.6.3=h2466b09_1
  - libparu=1.0.0=ss783_h21e6e03
  - librbio=4.3.4=ss783_hde22806
  - libsodium=1.0.20=hc70643c_0
  - libspex=3.2.1=ss783_hcfd7fc7
  - libspqr=4.3.4=ss783_hc35ff37
  - libsqlite=3.47.2=h67fdade_0
  - libssh2=1.11.1=he619c9f_0
  - libsuitesparseconfig=7.8.3=ss783_ha9923ec
  - libumfpack=6.3.5=ss783_h35348e5
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_8
  - libxml2=2.13.5=he286e8c_1
  - libzlib=1.3.1=h2466b09_2
  - markupsafe=3.0.2=py310h38315fa_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - metis=5.1.0=h17e2fc9_1007
  - mistune=3.1.0=pyhd8ed1ab_0
  - mkl=2024.2.2=h66d3029_15
  - mpfr=4.2.1=hbc20e70_3
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.5=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - openssl=3.4.0=ha4e3fda_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=24.3.1=pyh8b19718_2
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prometheus_client=0.21.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_1
  - psutil=6.1.1=py310ha8f682b_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.10.16=h37870fc_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.10=5_cp310
  - pytz=2024.2=pyhd8ed1ab_1
  - pywin32=307=py310h9e98ed7_3
  - pywinpty=2.0.14=py310h9e98ed7_0
  - pyyaml=6.0.2=py310ha8f682b_1
  - pyzmq=26.2.0=py310h656833d_3
  - referencing=0.35.1=pyhd8ed1ab_1
  - requests=2.32.3=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.22.3=py310hc226416_0
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=75.8.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - suitesparse=7.8.3=ss783_hf1e1ef2
  - tbb=2021.13.0=h62715c5_1
  - tbb-devel=2021.13.0=h47441b3_1
  - terminado=0.18.1=pyh5737063_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.4.2=py310ha8f682b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20241206=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - ucrt=10.0.22621.0=h57928b3_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.3.0=pyhd8ed1ab_0
  - vc=14.3=ha32ba9b_23
  - vc14_runtime=14.42.34433=he29a5d6_23
  - vs2015_runtime=14.42.34433=hdffcdeb_23
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.5=ha9f60a1_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zstandard=0.23.0=py310he5e10e1_1
  - zstd=1.5.6=h0ea2cb4_0
  - pip:
      - about-time==4.2.1
      - accessible-pygments==0.0.5
      - addict==2.3.0
      - alabaster==1.0.0
      - alive-progress==3.2.0
      - arviz==0.20.0
      - autograd==1.7.0
      - backports-tarfile==1.2.0
      - betterproto==2.0.0b6
      - cadet-process==0.10.0
      - cadet-python==1.0.4
      - cadet-rdm==0.0.42
      - click==8.1.8
      - cma==3.2.2
      - contourpy==1.3.1
      - corner==2.2.3
      - cryptography==44.0.0
      - cycler==0.12.1
      - deprecated==1.2.15
      - dill==0.3.9
      - diskcache==5.6.3
      - docutils==0.21.2
      - filelock==3.16.1
      - fonttools==4.55.3
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grapheme==0.6.0
      - greenlet==3.1.1
      - grpclib==0.4.7
      - h5netcdf==1.4.1
      - h5py==3.12.1
      - hagelkorn==1.2.3
      - hopsy==1.5.2
      - imagesize==1.4.1
      - ipylab==1.0.0
      - ipywidgets==8.1.5
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.1.0
      - joblib==1.4.2
      - junix==0.1.5
      - jupyter-cache==1.0.1
      - jupyterlab-widgets==3.0.13
      - jupytext==1.16.6
      - keyring==25.6.0
      - kiwisolver==1.4.8
      - latexcodec==3.0.0
      - llvmlite==0.43.0
      - markdown-it-py==3.0.0
      - matplotlib==3.9.0
      - mcbackend==0.5.2
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - more-itertools==10.5.0
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.17
      - myst-nb==1.1.2
      - myst-parser==4.0.0
      - numba==0.60.0
      - numpy==1.26.4
      - numpydoc==1.8.0
      - optlang==1.8.3
      - pandas==2.2.3
      - pathos==0.3.3
      - pillow==11.1.0
      - polyround==0.3.0
      - pox==0.3.5
      - ppft==1.7.6.9
      - pybtex==0.24.0
      - pybtex-docutils==1.0.3
      - pydata-sphinx-theme==0.16.1
      - pygithub==2.5.0
      - pyjwt==2.10.1
      - pymoo==0.6.1.3
      - pynacl==1.5.0
      - pyparsing==3.2.1
      - python-gitlab==5.3.1
      - pywin32-ctypes==0.2.3
      - requests-toolbelt==1.0.0
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - smmap==5.0.2
      - snowballstemmer==2.2.0
      - sphinx==8.1.3
      - sphinx-book-theme==1.1.3
      - sphinx-copybutton==0.5.2
      - sphinx-sitemap==2.6.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-bibtex==2.6.3
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - sqlalchemy==2.0.37
      - swiglpk==5.0.12
      - sympy==1.13.3
      - tabulate==0.9.0
      - threadpoolctl==3.5.0
      - tqdm==4.67.1
      - tzdata==2024.2
      - widgetsnbextension==4.0.13
      - wrapt==1.17.1
      - xarray==2025.1.1
      - xarray-einstats==0.8.0
prefix: C:\Users\ronal\mambaforge\envs\rdm_example
